In [2]:
import numpy as np
import pandas as pd

In [3]:
url = 'https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day27-one-hot-encoding/cars.csv'
df = pd.read_csv(url)

In [4]:
df.head()

,brand,km_driven,fuel,owner,selling_price
0,Maruti,145500,Diesel,First Owner,450000
1,Skoda,120000,Diesel,Second Owner,370000
2,Honda,140000,Petrol,Third Owner,158000
3,Hyundai,127000,Diesel,First Owner,225000
4,Maruti,120000,Petrol,First Owner,130000


In [74]:
print(df['brand'].value_counts().count())

32


In [6]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [7]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

## One Hot encode using Pandas

In [8]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False


In [9]:
# k-1 encoding 
# to remove first column
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False


We do not use this encoding method directly with Pandas because Pandas does not preserve the original column positions
the column order may change after encoding.

### One Hot Encoding using Sklearn

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2)

In [11]:
x_test.head()

,brand,km_driven,fuel,owner
3893,Maruti,50000,Petrol,First Owner
744,Mahindra,80000,Diesel,Third Owner
1045,Toyota,100000,Diesel,First Owner
1443,Maruti,41232,Diesel,First Owner
7379,Audi,35000,Diesel,Second Owner


In [12]:
y_test.head()

3893     135000
744      250000
1045     200000
1443     589000
7379    2000000
Name: selling_price, dtype: int64

In [13]:
y_train.head()

1311     200000
2648    2475000
2132     900000
4736     480000
1923    2280000
Name: selling_price, dtype: int64

In [17]:
from sklearn.preprocessing import OneHotEncoder

In [54]:
ohn = OneHotEncoder(drop='first',sparse_output=False)

In [56]:
new_x_train = ohn.fit_transform(x_train[['fuel','owner']])

In [57]:
print(new_x_train)

[[1. 0. 0. ... 1. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]


In [59]:
new_x_test = ohn.transform(x_test[['fuel','owner']])

In [60]:
print( new_x_test )

[[0. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 1.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]


to stack new_x_train and brand , km_driven

In [50]:
np.hstack((x_train[['brand','km_driven']].values,new_x_train))

array([['Ford', 104500, 1.0, ..., 1.0, 0.0, 0.0],
       ['Volvo', 2000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Mahindra', 60000, 1.0, ..., 0.0, 0.0, 0.0],
       ...,
       ['Mercedes-Benz', 7976, 1.0, ..., 0.0, 0.0, 0.0],
       ['Ford', 110000, 0.0, ..., 1.0, 0.0, 0.0],
       ['Tata', 3500, 0.0, ..., 0.0, 0.0, 0.0]], dtype=object)

In [51]:
np.hstack((x_train[['brand','km_driven']].values,new_x_train)).shape

(6502, 9)

### One Hot Encoding on brand column 

In [67]:
counts = df['brand'].value_counts()

In [68]:
df['brand'].nunique()
threshold=100

In [69]:
repl = counts[counts <= threshold].index

In [73]:
pd.get_dummies(df['brand'].replace(repl,'uncommon'),dtype=int)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
0,0,0,0,0,0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,1,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,0,0,0,0,1,0,0,0,0,0,0,0,0
8124,0,0,0,0,1,0,0,0,0,0,0,0,0
8125,0,0,0,0,0,0,1,0,0,0,0,0,0
8126,0,0,0,0,0,0,0,0,0,1,0,0,0
